Database:
  HOST: "127.0.0.1"
  PORT: "3306"
  DB: "azuriom"
  USER: "azpoints"
  PW: ""

Lang:
  msg-add: "&aVous venez d'ajouter %money% points a %player%."
  msg-take: "&aVous venez de prendre %money% points a %player%."
  msg-set: "&aVous venez de définir %money% points a %player%."
  no-permision: "&cVous n'avez pas la permission pour faire ceci."
  no-register: "&cLe joueur n'est pas inscrit sur le site"